# What is an API and how can I access one?

**Learning objectives:**

-   Explain what an API is.
-   Recognize how things communicate on the internet.
-   Compare and contrast web API frameworks.
-   Access an HTTP API with {httr2}.
-   Access a WebSocket API with {websocket}.

## APIs {-}

**API = "application programming interface"**

-   ðŸ¤– Allow programs to talk to one another
-   ðŸ’» Technically any function interface is an API

> "httr2 is a ground-up rewrite of httr that provides a pipeable ***API*** with an explicit request object that solves more problems felt by packages that wrap ***APIs***" (httr2 docs, emphasis added)

-   ðŸ•¸ï¸ Focus = ***web*** APIs
    -   For rest of book, "API" means "web API"

## HTTP {-}

-   HTTP(S) = most of internet communication
-   Request methods (in ~order of use):
    -   GET (fetch something)
    -   POST (push something)
    -   DELETE, PUT, PATCH (change things)
    -   CONNECT, OPTIONS, HEAD, TRACE (I didn't know these existed)
-   Request = URL + headers + method + body

## API Frameworks {-}

-   RPC = Remote Procedure Call
    -   Endpoints = actions
    -   XML-RPC & JSON-RPC popular early
    -   Often just GET ("GET /deleteItem/1234")
-   SOAP = Simple Objects Access Protocol (briefly huge, mostly dead)
-   REST = REpresentational State Transfer
    -   Most common by far
    -   Stateless (call defines the object)
    -   Technically endpoints = nouns
    
## API Frameworks (cont) {-}

-   GraphQL = Graph Query Language
    -   Body defines everything
    -   Basically GET + 1 endpoint
-   gRPC = (Google? General?) RPC
    -   Becoming very popular
    -   Good for real-time, 2-way communication
    -   Uses HTTP/2 (more socket-like)

## httr2 {-}

-   Pipe-based API calls
-   Working with dev (will be released ~soon as 1.0.0)
-   `request |> perform |> resp (parse)`

## httr2 demo {-}

```{r 04-httr2-demo}
httr2::request("https://api.open.fec.gov/v1") |> 
  httr2::req_headers("X-Api-Key" = "DEMO_KEY") |> 
  httr2::req_url_path_append("candidates") |> 
  httr2::req_url_query(office = c("H", "S"), .multi = "explode") |> 
  httr2::req_perform() |> 
  httr2::resp_body_json() |> 
  _$results |> 
  tibblify::tibblify(unspecified = "list") |> 
  dplyr::glimpse()
```

## httr2 more to come {-}

-   Deeper dive in (new) chapter 5
-   Auth in chapter 6

## WebSocket {-}

-   Alternative to HTTP
-   `ws://` or `wss://`
-   2-way communication
-   EMBED A DEMO HERE

## Meeting Videos {-}

### Cohort 1 {-}

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
