project:
  type: website

website:
  title: "Web APIs with R Book Club"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/r4ds/bookclub-wapir
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PL3x6DOfs2NGg-zPCeSCSp7tkkQBZNLDzv
      - icon: mastodon
        href: https://fosstodon.org/@jonthegeek
      - icon: linkedin
        href: https://www.linkedin.com/in/jonthegeek/
    contents:
      - index.qmd
      - file: slides/club-intro.qmd
        target: wapir-club_club_intro
      - file: slides/intro.qmd
        target: wapir-club_intro
      - file: slides/los.qmd
        target: wapir-club_los

      - section: "How can I interact with the web from R?"
        contents:
          - file: slides/httr2/apis-start.qmd
            target: wapir-club_apis-start
          - file: slides/httr2/schemas.qmd
            target: wapir-club_schemas
          - file: slides/httr2/httr2.qmd
            target: wapir-club_httr2
          - file: slides/httr2/httr2-authentication.qmd
            target: wapir-club_httr2-authentication
          - file: slides/httr2/httr2-responses.qmd
            target: wapir-club_httr2-responses
          - file: slides/httr2/httr2-perform.qmd
            target: wapir-club_httr2-perform
          - file: slides/httr2/httr2-methods.qmd
            target: wapir-club_httr2-methods
          - file: slides/httr2/apis-find.qmd
            target: wapir-club_apis-find
          - file: slides/httr2/apis-packages.qmd
            target: wapir-club_apis-packages
          - file: slides/httr2/accessing-other.qmd
            target: wapir-club_accessing-other
          - file: slides/httr2/rvest.qmd
            target: wapir-club_rvest
          - file: slides/httr2/accessing-more.qmd
            target: wapir-club_accessing-more

      - section: "How can I create my own APIs with R?"
        contents:
          - file: slides/plumber/plumber-intro.qmd
            target: wapir-club_plumber-intro
          - file: slides/plumber/plumber-input.qmd
            target: wapir-club_plumber-input
          - file: slides/plumber/plumber-output.qmd
            target: wapir-club_plumber-output
          - file: slides/plumber/plumber-errors.qmd
            target: wapir-club_plumber-errors
          - file: slides/plumber/plumber-security.qmd
            target: wapir-club_plumber-security
          - file: slides/plumber/plumber-test.qmd
            target: wapir-club_plumber-test
          - file: slides/plumber/plumber-deploy.qmd
            target: wapir-club_plumber-deploy
          - file: slides/plumber/creating-more.qmd
            target: wapir-club_creating-more

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
