project:
  type: website

website:
  title: "Web APIs with R Book Club"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/r4ds/bookclub-wapir
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PL3x6DOfs2NGg-zPCeSCSp7tkkQBZNLDzv
      - icon: mastodon
        href: https://fosstodon.org/@jonthegeek
      - icon: linkedin
        href: https://www.linkedin.com/in/jonthegeek/
    contents:
      - index.qmd
      - file: slides/club-intro.qmd
        target: wapir_club-club_intro
      - file: slides/intro.qmd
        target: wapir_club-intro

      - section: "Get started"
        contents:
          - file: slides/httr2/apis-start.qmd
            target: wapir_club-apis_start
          - file: slides/httr2/schemas.qmd
            target: wapir_club-schemas
          - file: slides/httr2/httr2.qmd
            target: wapir_club-httr2
          - file: slides/httr2/httr2-authentication.qmd
            target: wapir_club-httr2-authentication

      - section: "Get more data"
        contents:
          - file: slides/httr2/httr2-pagination.qmd
            target: wapir_club-httr2-pagination
          - file: slides/httr2/rvest.qmd
            target: wapir_club-rvest
          - file: slides/httr2/httr2-responses.qmd
            target: wapir_club-httr2-responses
          - file: slides/httr2/apis-find.qmd
            target: wapir_club-apis-find

      - section: "Do more with APIs"
        contents:
          - file: slides/httr2/httr2-methods.qmd
            target: wapir_club-httr2-methods
          - file: slides/httr2/accessing-other.qmd
            target: wapir_club-accessing_other
          - file: slides/httr2/accessing-more.qmd
            target: wapir_club-accessing-more

      - section: "Appendices"
        contents:
          - file: slides/los.qmd
            target: wapir_club-los
          - file: slides/leftovers.qmd
            target: wapir_club-leftovers

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
