project:
  type: website

website:
  title: "Web APIs with R Book Club"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/dslc/club-wapir
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PL3x6DOfs2NGg-zPCeSCSp7tkkQBZNLDzv
      - icon: mastodon
        href: https://fosstodon.org/@jonthegeek
      - icon: linkedin
        href: https://www.linkedin.com/in/jonthegeek/
    contents:
      - index.qmd
      - file: slides/club-intro.qmd
        target: wapir_club-club_intro
      - file: slides/intro.qmd
        target: wapir_club-intro

      - section: "Get started"
        contents:
          - file: slides/apis-start.qmd
            target: wapir_club-apis_start
          - file: slides/schemas.qmd
            target: wapir_club-schemas
          - file: slides/httr2.qmd
            target: wapir_club-httr2
          - file: slides/authentication.qmd
            target: wapir_club-authentication

      - section: "Get more data"
        contents:
          - file: slides/pagination.qmd
            target: wapir_club-pagination
          - file: slides/rvest.qmd
            target: wapir_club-rvest
          - file: slides/responses.qmd
            target: wapir_club-responses

      - section: "Do more with APIs"
        contents:
          - file: slides/httr2-other.qmd
            target: wapir_club-httr2-other
          - file: slides/apis-find.qmd
            target: wapir_club-apis-find
          - file: slides/accessing-other.qmd
            target: wapir_club-accessing_other
          - file: slides/learn-more.qmd
            target: wapir_club-learn-more

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
