project:
  type: website

website:
  title: "Web APIs with R Book Club"
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        href: https://github.com/r4ds/bookclub-wapir
      # - icon: youtube
      #   href: https://r4ds.io/youtube
      - icon: mastodon
        href: https://fosstodon.org/@jonthegeek
      - icon: linkedin
        href: https://www.linkedin.com/in/jonthegeek/
    contents:
      - index.qmd
      - file: slides/club-intro.qmd
        target: _blank
      - file: slides/intro.qmd
        target: _blank

      - section: "How can I get web data into R?"
        contents:
          - file: slides/httr2/apis.qmd
            target: _blank
          - file: slides/httr2/httr2.qmd
            target: _blank
          - file: slides/httr2/httr2-authentication.qmd
            target: _blank
          - file: slides/httr2/httr2-responses.qmd
            target: _blank
          - file: slides/httr2/httr2-perform.qmd
            target: _blank
          - file: slides/httr2/apis-find.qmd
            target: _blank
          - file: slides/httr2/apis-packages.qmd
            target: _blank
          - file: slides/httr2/accessing-other.qmd
            target: _blank
          - file: slides/httr2/rvest.qmd
            target: _blank
          - file: slides/httr2/accessing-more.qmd
            target: _blank

      - section: "How can I create my own APIs with R?"
        contents:
          - file: slides/plumber/plumber-intro.qmd
            target: _blank
          - file: slides/plumber/plumber-input.qmd
            target: _blank
          - file: slides/plumber/plumber-output.qmd
            target: _blank
          - file: slides/plumber/plumber-errors.qmd
            target: _blank
          - file: slides/plumber/plumber-security.qmd
            target: _blank
          - file: slides/plumber/plumber-test.qmd
            target: _blank
          - file: slides/plumber/plumber-deploy.qmd
            target: _blank
          - file: slides/plumber/creating-more.qmd
            target: _blank

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
