# How do computers communicate?

**Learning objectives:**

-   Explain what an API is.
-   Identify the pieces of an HTTP request. 
-   Describe how accessing a web page through a browser involves an HTTP request.
-   Compare and contrast HTTP-based API frameworks.
-   Recognize other web API protocols.

## APIs {-}

**API = "application programming interface"**

-   🤖 Allow programs to talk to one another
-   💻 Technically any function interface is an API

> "httr2 is a ground-up rewrite of httr that provides a pipeable ***API*** with an explicit request object that solves more problems felt by packages that wrap ***APIs***" (httr2 docs, emphasis added)

-   🕸️ Focus = ***web*** APIs
    -   For rest of book, "API" means "web API"
    -   Web API = API on the internet

## HTTP {-}

-   HTTP = HyperText Transfer Protocol ("way to move web pages")
-   HTTP(S) = most of internet communication
-   Request methods (in ~order of use):
    -   GET (fetch existing thing)
    -   POST (push new thing)
    -   DELETE, PUT, PATCH (change existing thing)
    -   CONNECT, OPTIONS, HEAD, TRACE (I didn't know these existed)
-   Request = URL + headers + method + body

## Browsers and HTTP Requests {-}

https://jonthegeek.github.io/wapir/apis.html is an HTTP request:

-   `https://` = "use HTTP(s) protocol"
-   `jonthegeek.github.io/wapir/apis.html` = URL
-   Cookies, etc sent as invisible headers
-   `GET` = protocol
-   Empty body

## HTTP API Frameworks: Historic {-}

-   RPC = Remote Procedure Call
    -   Endpoints = actions
    -   XML-RPC & JSON-RPC popular early
    -   Often just GET ("GET /deleteItem/1234")
-   SOAP = Simple Objects Access Protocol (briefly huge, mostly dead)
    -   Evolved from XML-RPC
    -   Technically not limited to HTTP

## HTTP API Frameworks: Modern {-}

-   REST = REpresentational State Transfer
    -   Most common by far
    -   Stateless (call defines the object)
    -   Technically endpoints = nouns
    -   What we'll focus on in most of book
-   GraphQL = Graph Query Language
    -   Body defines everything
        -   JSON with wildcards telling server what to fill in
    -   Basically GET + 1 endpoint
    -   Will probably get its own chapter

## Other API Frameworks {-}

-   websocket
    -   Alternative to HTTP
    -   `ws://` or `wss://`
    -   2-way communication
    -   {websocket} package
-   gRPC = Google RPC
    -   Becoming very popular
    -   Good for real-time, 2-way communication
    -   Uses HTTP/2 (more socket-like)

Deeper dive coming in Chapter 9!

## Meeting Videos {-}

### Cohort 1 {-}

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
